Build uniform grid in 1d fit
HERA-Team/uvtools pull request #112
Opened 2021-04-22 01:33 UTC by aewallwi

Allow _fit_basis_1d to handle missing data. Missing data causes the x-axis to not be uniformly spaced but it is spaced by integer multiples of a fundamental dx so we can fill in these gaps with flagged weight zero data to make the basis fitting behave and then throw away these points when we return the model fits.

2021-04-30 19:39 UTC, r-pascua requested changes
This looks like a useful update that allows for easy processing of data that has gaps due to spurious dropouts; however, there are a few changes I would like to see to the new function (in particular, just some variable name changes and a bit of improvement of the documentation). In addition to the comments I left in this review, I think it would be nice for the new function to have a section of examples that show the user the expected behavior of the function.

On another note, I think that the testing changes should be their own PR. I have done a very large testing overhaul before, and it is a pretty monstrous process to get everything right, though it is very much worth the effort if the intention is to set a higher bar for testing. There is good progress on converting to ``pytest``-only, but there is still much work left to be done to improve the tests. I think that moving all the testing updates to a new branch and saving it for a different PR will serve to make the job of reviewing easier, keep the changes more modular, and let this PR get merged faster.

Thank you for all the work!

2021-05-01 02:08 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    pytest.raises(ValueError, dspec.gen_window, 'bh', 200, edgecut_hi=101, edgecut_low=100)
This is now in a different PR.

2021-05-03 17:43 UTC, aewallwi commented on uvtools/dspec.py
> +              boolean array indicating which x-values were inserted.
fixed.

2021-05-03 17:48 UTC, aewallwi commented on uvtools/dspec.py
> +        on an incomplete grid.
I've beefed up the docstring and added more descriptive variable (w -> weights, y -> data).

2021-05-03 17:50 UTC, aewallwi commented on uvtools/dspec.py
> +    dx = np.abs(np.diff(x)).min() * np.sign(np.diff(x)[0])
yes.

2021-05-03 17:55 UTC, aewallwi commented on uvtools/dspec.py
> +        if not np.isclose(integer_spacing, grid_spacing, rtol=0, atol=xtol):
Thanks for catching this! I did indeed mean to have `atol = dx * xtol` and changed to this.

2021-05-03 22:34 UTC, aewallwi commented on uvtools/dspec.py
> +            return xout, yout, wout, inserted
I've added coverage for this.

2021-05-03 22:34 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    for m in range(100):
make sure that we don't visit a special case. I've reduced this to two times.

2021-05-03 22:41 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    wt = np.ones(len(xt))
Great tip! This will save me a lot of testing code in the future :).

2021-05-03 22:48 UTC, aewallwi commented on uvtools/dspec.py
> +    wout = np.zeros(xout.shape, dtype=np.float)
I've changed to this system.

2021-05-03 22:49 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert dspec.wedge_width(100., .001, 100, horizon=2.) == (21,-20)
Move this comment to #116

2021-05-03 22:49 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    TOL = 1e-6
Move this comment to #116

2021-05-03 22:49 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert info['status']['axis_1'][1] == 'success'
Move this comment to #116.

2021-05-03 22:49 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    pytest.raises(ValueError, dspec.fourier_model, np.empty((3, 3)), NFREQS)
Move this comment to #116

2021-05-03 22:50 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +                     data[0], flags[0], sigma, nmax=3, cn_guess=np.array([3]))
Move this comment #116

2021-05-03 22:50 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert np.all((frs[u:l] < -1e-2) | (frs[u:l] > 2e-2))
Move this comment to #116

2021-05-03 22:50 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +        assert np.all(np.isclose(win, win3*np.sqrt(np.mean(win**2.)),atol=1e-6))
Move this comment to #116

2021-05-03 23:21 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert info['status']['axis_1'][0] == 'skipped'
Move to #117

2021-05-03 23:28 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert not np.any([info['status']['axis_1'][i] == 'skipped' for i in list(info['status']['axis_1'])[1:]])
Moved to #117

2021-05-03 23:37 UTC, aewallwi commented
Thanks for the review @r-pascua, especially the helpful pytest tips. I've restricted this PR to only address the 1d gridding stuff. I've moved the remainder of pytest migration to #116 (which is translating the existing tests verbatum into pytest compatible lines and tweaking the imports and test dir structure to accomodate codecov). I've moved the suggestions on reorganizing the existing tests (which is beyond the verbatum pytest translation) into their own issues which can be addressed in #117

2021-05-04 03:38 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +        assert np.allclose(wout[to_keep], wt[to_keep])
I've broken this test up.

2021-05-04 03:38 UTC, aewallwi commented on uvtools/tests/test_dspec.py
> +    assert np.allclose(resid5, resid6[to_keep])
I've broken this out.

2021-05-05 04:59 UTC, r-pascua approved these changes
I think the documentation is much clearer now, thank you! It looks like some changes you marked as resolved haven't been pushed yet--can you make sure that the remote branch is up-to-date with your local branch?

It looks like the new tests have improved relative to the original round of tests written, though the change to `.coveragerc` that was reverted seems to make it so that the coverage tool doesn't think that any of the new code is covered by tests. Is that being fixed in the PR dealing with migrating to `pytest`-only?

All that said, I think I'm happy to approve the changes. I trust that you'll get the minor changes I mentioned pushed, so go ahead and merge the PR once that's finished. Thank you for all your work!

2021-05-05 04:59 UTC, r-pascua commented on uvtools/dspec.py
> +        if not np.isclose(integer_spacing, grid_spacing, rtol=0, atol=xtol):
I think that this change wasn't actually pushed yet? It looks like it still says `atol=xtol` on my end.

2021-05-05 17:31 UTC, aewallwi commented on uvtools/dspec.py
> +        if not np.isclose(integer_spacing, grid_spacing, rtol=0, atol=xtol):
Good catch. I've fixed this.

2021-05-05 20:00 UTC, merged